update changes, formatting

diff --git a/scripts/utils/distroboxRestartAll b/scripts/utils/distroboxRestartAll
--- a/scripts/utils/distroboxRestartAll
+++ b/scripts/utils/distroboxRestartAll
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 distrobox list --no-color | awk 'NR>1 {print $3}' | while read name; do
-    echo "restarting: $name"
+	echo "restarting: $name"
 
-    distrobox stop "$name" -Y || echo "stop failed"
-    distrobox enter "$name" -- bash -c 'echo started' </dev/null || echo "enter failed"
+	distrobox stop "$name" -Y || echo "stop failed"
+	distrobox enter "$name" -- bash -c 'echo started' </dev/null || echo "enter failed"
 done
